### ISSUE TITLE
bug fix: React complains about PropTypes.shape

### ISSUE THREAD

**Issue by Domiii** [tjindapitak/react-text-ellipsis#14]
Replaced invalid use of PropTypes.shape with PropTypes.object.

React prints this to console on every render call in development mode:

> type specification of prop `style` is invalid; the type checker function must return `null` or an `Error` but returned a function. You may have forgotten to pass an argument to the type checker creator (arrayOf, instanceOf, objectOf, oneOf, oneOfType, and shape all require an argument).

------------

Already submitted PR: #13

**Comment by tjindapitak** [comment]
Thanks #13 is merged
