### ISSUE TITLE
React should be a peerDependency

### ISSUE THREAD

**Issue by lexanth** [tjindapitak/react-text-ellipsis#16]
You've currently got react as a hard dependency and limited to v15.
React should be a peerDependency so it takes the React version that you've got in your application. Also, the range should be updated to allow v16. It's probably also a devDependency.

For example, react-redux has this as a peer dependency:
`"react": "^0.14.0 || ^15.0.0-0 || ^16.0.0-0",`

Not too fussed about 14, but this definitely works in 16.

**Comment by tjindapitak** [comment]
Thanks,
fixed
